# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job to build and upload the armadillo conan recipe
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install gfortran
        run: sudo apt install -y gfortran
      # Runs a set of commands using the runners shell
      - name: Install conan and conan_package_tools
        run: |
          pip install --upgrade conan
          pip install --upgrade conan_package_tools
      - name: Login into conan
        run: conan user
      
      # Runs a set of commands using the runners shell
      - name: Build the package
        env: 
          CONAN_USERNAME: "darcamo"
          CONAN_LOGIN_USERNAME: "darcamo"
          CONAN_CHANNEL: "stable"
          CONAN_UPLOAD: "https://api.bintray.com/conan/darcamo/cppsim"
          CONAN_BUILD_POLICY: "missing"
        run: python build.py
          
